sudo: required
services:
  - docker

before_install:
  - docker build -t chadftest/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chadftest/react-test npm test

after_success:
  - docker build -t chadftest/multi-client ./client
  - docker build -t chadftest/multi-nginx ./nginx
  - docker build -t chadftest/multi-server ./server
  - docker build -t chadftest/multi-worker ./worker